# Exercise 5.A NumPy Fundamentals

This notebook explores the basics of the NumPy library, including
creating arrays, checking data types, indexing, slicing, transposing,
and working with multi-dimensional arrays.

In [1]:
import numpy as np

In [2]:
## Array Basics

In [3]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [4]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
print(arr_1.dtype)

<U6


In [6]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [7]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [8]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [9]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [10]:
# arr_3[0, 2] = row 0, col 2 = value 5
# arr_3[1, 1] = row 1, col 1 = value 4
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)

[5 4]


In [11]:
# np.ones() creates an array filled with 1s
# shape (2, 2, 2) = 2 layers, 2 rows, 2 columns
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
