# Exercise 1.A NumPy: Manipulating Arrays

In [31]:
import numpy as np

## Looping Through Arrays

In [32]:
# Create a 2D array with two rows: (11,12,13) and (14,15,16)
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [33]:
# Loop through the first dimension of arrA — each 'x' is a row (a 1D array)
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [34]:
# Loop through the second dimension of arrA — each 'y' is a single scalar element
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


Difference: The first loop iterates over the two rows of arrA, printing each row (a 1-D array) multiplied by 2. The second loop iterates over individual elements, so each number is printed on its own line.

In [35]:
# Loop through the second dimension again, but this time assign x*2 to loop_result
for x in arrA:
    for y in x:
        loop_result = x * 2  # x*2 multiplies the whole row, not just y
        print(loop_result)
# loop_result is a full row array each time — y is unused here. 
# loop_result stores x*2, which doubles the entire row, not just the individual element y. 
# This means the full doubled row is printed once per element (6 times total), rather than one doubled value per element.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [36]:
# Concatenate arrA with arrA on axis=0 (default) — stacks rows on top of each other
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [37]:
# Concatenate arrA with arrA on axis=1 — joins columns side by side
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [38]:
# Stack joined_array_1 with itself on the default axis (axis=0)
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [39]:
# Stack joined_array_1 with joined_array_2 
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

# ValueError: all input arrays must have the same shape
# joined_array_1 is (4,3) and joined_array_2 is (2,6) — shapes don't match

ValueError: all input arrays must have the same shape

In [40]:
# Concatenate joined_array_1 with arrA on the default axis (axis=0)
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [41]:
# Concatenate joined_array_1 with arrA on axis=1
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# When joining on axis=1 (side by side), numpy requires both arrays to have the
# same number of ROWS. joined_array_1 has 4 rows but arrA only has 2 rows,
# so numpy can't line them up column-by-column — the row counts don't match.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [42]:
# hstack: horizontal stack — joins arrays side by side (along axis=1 for 2D arrays)
hstacked = np.hstack((arrA, arrA))
print("hstack result:")
print(hstacked)
# hstack glues arrA to the right of arrA, increasing the number of columns.
# Result shape: (2, 6)

# vstack: vertical stack — joins arrays on top of each other (along axis=0)
vstacked = np.vstack((arrA, arrA))
print("\nvstack result:")
print(vstacked)
# vstack places arrA below arrA, increasing the number of rows.
# Result shape: (4, 3)

# dstack: depth stack — joins arrays along the THIRD axis (depth), creating a 3D array
dstacked = np.dstack((arrA, arrA))
print("\ndstack result:")
print(dstacked)
# dstack layers arrA behind arrA along a new third dimension.
# Result shape: (2, 3, 2)

hstack result:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

vstack result:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

dstack result:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [43]:
# Split joined_array_1 into 2 equal parts along axis=0 (default)
splitsky = np.split(joined_array_1, 2)
print(splitsky)

# splitsky is a Python LIST containing 2 arrays.
# Each of those arrays is 2-dimensional with shape (2, 3) — 2 rows and 3 columns.
# The split divided joined_array_1's 4 rows into two groups of 2 rows each.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [44]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# Result: a Python list of 3 arrays — two with 2 rows, one with 0 rows (empty)
# Each sub-array is still 2-D

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [45]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [46]:
# Create arrB as a 2D array with rows (7,6), (13,5), (7,3)
arrB = np.array([[7, 6], [13, 5], [7, 3]])

# Sort arrB
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [47]:
# Print arrB 
print(arrB)

# Create boolean mask z: True where values in arrB are less than 7
z = arrB < 7

# Apply the mask — arrB[z] returns a 1D array of all values where z is True
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [48]:
# Create boolean mask y: True where values in arrB are greater than or equal to 7
y = arrB >= 7

# Apply the mask — arrB[y] returns all values that satisfy the condition
arrD = arrB[y]
print(arrD)

[ 7 13  7]
