# Exercise 1.B NumPy Random

In [30]:
import numpy as np

## Generating Random Numbers

In [31]:
# Random integers between 1 and 20, 2 elements (1D)
r_1 = np.random.randint(1, 21, size=2)
print(r_1)

[18 19]


In [32]:
# Random integers between 1 and 20, 1 row and 2 columns
r_2 = np.random.randint(1, 21, size=(1,2))
print(r_2)

[[14  3]]


In [33]:
# Random floats between 0 and 1, 2 rows and 1 column
r_3 = np.random.random((2, 1))
print(r_3)

[[0.00657341]
 [0.9780858 ]]


In [34]:
# Random integers between 20 and 100, 4 rows and 5 columns
r_4 = np.random.randint(20, 101, size=(4, 5))
print(r_4)

[[90 64 24 98 62]
 [75 62 96 38 70]
 [88 25 82 38 70]
 [85 74 41 51 74]]


In [35]:
# Random floats between 0 and 1, 4 rows and 5 columns
r_5 = np.random.random(size=(4, 5))
print(r_5)

[[0.78574988 0.22195483 0.15337579 0.00260704 0.55332135]
 [0.5040973  0.70756907 0.12972418 0.26814266 0.74049239]
 [0.28311818 0.57465099 0.44558658 0.7307982  0.62819841]
 [0.30609615 0.6512953  0.99830851 0.28764278 0.73900495]]


## Generating Random Choices from an Array

In [36]:
# 1D array of 12 classmate names
students = np.array([
    'Alice', 'Brian', 'Carlos', 'Diana',
    'Evelyn', 'Frank', 'Grace', 'Henry',
    'Isabel', 'James', 'Karen', 'Luis'
])

In [37]:
# Choose one random student from the array
call_on = np.random.choice(students)
print(call_on)

James


In [38]:
# Choose one random student from the array
call_on = np.random.choice(students)
print(call_on)

Evelyn


In [39]:
# Choose a random sample from students in a 3x4 grid (3 rows, 4 columns = 12 selections)
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)

# This is not an effective way to assign breakout groups because np.random.choice can repeat students,
# so some may appear multiple times while others are left out. 
# A better approach would ensure each student is selected only once using replace=False.

[['Carlos' 'Carlos' 'Isabel' 'Isabel']
 ['Isabel' 'Grace' 'Grace' 'Isabel']
 ['Diana' 'Isabel' 'Alice' 'Brian']]


In [46]:
# Choose 5 students with weighted probabilities
# Probabilities must sum to 1.0 and there must be one value per student
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.05, 0.30, 0.10, 0.10, 0.10, 0.10, 0.05, 0.10, 0.05, 0.05, 0.00, 0.00]
)
print(call_on_weighted)

# Probability breakdown (p values must sum to 1.0):
# Alice   = 0.05  — low chance
# Brian   = 0.30  — highest chance (30% as required)
# Carlos  = 0.10
# Diana   = 0.10
# Evelyn  = 0.10
# Frank   = 0.10
# Grace   = 0.05  — low chance
# Henry   = 0.10
# Isabel  = 0.05  — low chance
# James   = 0.05  — low chance
# Karen   = 0.00  — zero likelihood of being called on (as required)
# Luis    = 0.00  — zero likelihood of being called on (as required)

['Frank' 'Henry' 'Frank' 'Grace' 'Brian']


## Generating a Normal Distribution

In [41]:
# Normal distribution: mean=10, standard deviation=5, size=4x5
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[16.27547139  5.68226999  2.09241654 10.0181527   7.9689762 ]
 [ 6.40032832 14.42288955 19.16865701 10.51079556  1.86067189]
 [ 7.55387855  5.52133225  7.76144241  6.87673094 11.80640816]
 [16.24584262  3.34200122 12.07123262 19.89623711 13.54481632]]
