# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
# Copied from Exercise 1.B
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

## Permutations

In [3]:
# Print current value of r_4
print(r_4)

[[49 50 20 26 56]
 [87 97 62 54 39]
 [35 57 99 74 29]
 [54 79 32 24 52]]


In [11]:
print(r_1)

[16 17]


In [5]:
# Shuffle r_4 in place
np.random.shuffle(r_4)
print(r_4)

[[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]]


**Shuffle observation:** `np.random.shuffle` only shuffles along the **x axis** — meaning it rearranges the rows as whole units, but does not change the order of elements within each row. The values inside each row stay together; only which row appears in which position changes.

In [6]:
# Create a permutation of r_4 
new_shuffle = np.random.permutation(r_4)
print('new_shuffle:')
print(new_shuffle)

print('r_4 (unchanged):')
print(r_4)

new_shuffle:
[[35 57 99 74 29]
 [87 97 62 54 39]
 [49 50 20 26 56]
 [54 79 32 24 52]]
r_4 (unchanged):
[[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]]


**Shuffle vs Permutation:** Use `shuffle` when we want to randomly reorder an existing array in place and don't need to keep the original order. Use `permutation` when we want a new randomly ordered copy while preserving the original array-useful when we still need to reference the original data after reordering.

## Mathematical Operations

In [7]:
# r_1 + r_2: shape (2,) and (1,2)
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_2:', r_2, '| shape:', r_2.shape)
result = np.add(r_1, r_2)
print('r_1 + r_2:', result)
print('Result shape:', result.shape)

r_1: [16 17] | shape: (2,)
r_2: [[15 15]] | shape: (1, 2)
r_1 + r_2: [[31 32]]
Result shape: (1, 2)


In [8]:
# r_1 + r_3: shape (2,) and (2,1)
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_3:', r_3, '| shape:', r_3.shape)
result = np.add(r_1, r_3)
print('r_1 + r_3:', result)
print('Result shape:', result.shape)

r_1: [16 17] | shape: (2,)
r_3: [[0.35122374]
 [0.26960524]] | shape: (2, 1)
r_1 + r_3: [[16.35122374 17.35122374]
 [16.26960524 17.26960524]]
Result shape: (2, 2)


In [12]:
print('r_2:', r_2, '| shape:', r_2.shape)
print('r_3:', r_3, '| shape:', r_3.shape)
result = np.add(r_2, r_3)
print('r_2 + r_3:', result)
print('result shape:', result.shape)

r_2: [[15 15]] | shape: (1, 2)
r_3: [[0.35122374]
 [0.26960524]] | shape: (2, 1)
r_2 + r_3: [[15.35122374 15.35122374]
 [15.26960524 15.26960524]]
result shape: (2, 2)


In [21]:
print('r_1:', r_1, '| shape:', r_1.shape)
print('r_4:', r_4, '| shape:', r_4.shape)
result = np.add(r_1, r_4)
print('r_1 + r_4:', result)
print('result shape:', result.shape)

# r_1 cannot broadcast with r_4 because of the different shapes, (2,) and (4,5) respectively.

r_1: [16 17] | shape: (2,)
r_4: [[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]] | shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [22]:
# r_2 + r_4: shape (1,2) and (4,5)
print('r_2:', r_2, '| shape:', r_2.shape)
print('r_4:', r_4, '| shape:', r_4.shape)
result = np.add(r_2, r_4)
print('r_2 + r_4:', result)
print('Result shape:', result.shape)

# r_2 cannot broadcast with r_4 because of the different shapes, (1,2) and (4,5) respectively.

r_2: [[15 15]] | shape: (1, 2)
r_4: [[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]] | shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [23]:
print('r_3:', r_3, '| shape:', r_3.shape)
print('r_4:', r_4, '| shape:', r_4.shape)
result = np.add(r_3, r_4)
print('r_3 + r_4:', result)
print('result shape:', result.shape)

# r_3 cannot broadcast with r_4 because of the different shapes, (2,1) and (4,5) respectively.

r_3: [[0.35122374]
 [0.26960524]] | shape: (2, 1)
r_4: [[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]] | shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

In [16]:
# Add np.array([1]) to r_4 
print(np.add(np.array([1]), r_4))

#single element broadcasts across the entire array

[[ 55  80  33  25  53]
 [ 50  51  21  27  57]
 [ 36  58 100  75  30]
 [ 88  98  63  55  40]]


In [17]:
# Add np.array([[1]]) to r_4 
print(np.add(np.array([[1]]), r_4))

#2D single element also broadcasts across the entire array

[[ 55  80  33  25  53]
 [ 50  51  21  27  57]
 [ 36  58 100  75  30]
 [ 88  98  63  55  40]]


In [18]:
# Add np.array([1,1,1,1,1]) to r_4 
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))

#shape (5,) matches 5 columns, broadcasts across all 4 rows

[[ 55  80  33  25  53]
 [ 50  51  21  27  57]
 [ 36  58 100  75  30]
 [ 88  98  63  55  40]]


In [24]:
# Add np.array([[1],[1]]) to r_4 
print(np.add(np.array([[1],[1]]), r_4))

# ERROR: operands could not be broadcast together with shapes (2,1) and (4,5).
# The first dimension is 2, which does not match r_4's 4 rows and is not 1,
# so numpy cannot stretch it to fit.

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

**How broadcasting works:** When adding two arrays, numpy compares their shapes dimension by dimension from right to left. A dimension is compatible if the sizes are equal, or if one of them is 1, in that case, the size-1 dimension gets "stretched" to match the other. The shape of the result is the larger of the two sizes in each dimension. If any dimension is neither equal nor 1, numpy raises a ValueError. So `np.array([1])` added to a (4,5) array adds 1 to every single element, while `np.array([1,1,1,1,1])` adds element-by-element across each row.

## Rounding

In [25]:
# Print r_3 to see the float values we'll be rounding
print(r_3)

[[0.35122374]
 [0.26960524]]


In [26]:
# trunc: removes the decimal part, returning the integer portion (toward zero)
print(np.trunc(r_3))

[[0.]
 [0.]]


In [27]:
# fix: same as trunc — truncates toward zero
print(np.fix(r_3))

[[0.]
 [0.]]


In [28]:
# floor: rounds DOWN to the nearest integer
print(np.floor(r_3))

[[0.]
 [0.]]


In [29]:
# ceil: rounds UP to the nearest integer
print(np.ceil(r_3))

[[1.]
 [1.]]


In [30]:
# round: rounds to 2 decimal places using standard rounding rules
print(np.round(r_3, 2))

[[0.35]
 [0.27]]


## Cumulative Operations

In [31]:
# Print r_4 to see the values we'll be summing
print(r_4)

[[54 79 32 24 52]
 [49 50 20 26 56]
 [35 57 99 74 29]
 [87 97 62 54 39]]


In [32]:
# Sum of ALL values in r_4 
print(np.sum(r_4))

1075


In [33]:
# Sum along axis=0
print(np.sum(r_4, axis=0))

[225 283 213 178 176]


In [34]:
# Sum of ALL values in r_4 
print(np.sum(r_4))

1075


In [35]:
# Sum along axis=1
print(np.sum(r_4, axis=1))

[241 201 294 339]


In [36]:
# Cumulative sum of all values in r_4 
print(np.cumsum(r_4))

[  54  133  165  189  241  290  340  360  386  442  477  534  633  707
  736  823  920  982 1036 1075]


In [37]:
# Cumulative sum along axis=0
print(np.cumsum(r_4, axis=0))

[[ 54  79  32  24  52]
 [103 129  52  50 108]
 [138 186 151 124 137]
 [225 283 213 178 176]]


## Grocery Problem

In [38]:
# Each array represents [vegetables, fruits, snacks, beverages]
bag1 = np.array([2, 3, 4, 0])  # 2 vegetables, 3 fruits, 4 snacks, 0 beverages
bag2 = np.array([4, 0, 1, 2])  # 4 vegetables, 0 fruits, 1 snack, 2 beverages
print('bag1:', bag1)
print('bag2:', bag2)

bag1: [2 3 4 0]
bag2: [4 0 1 2]


In [39]:
# Total items per bag
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)
print(f'The first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [40]:
# Total items per category across both bags
category_totals = np.add(bag1, bag2)
print(f'There are {category_totals[0]} vegetables, {category_totals[1]} fruits, '
      f'{category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [41]:
# Ali: Mon=5, Tue=4, Wed=6, Thu=4, Fri=2
ali = np.array([5, 4, 6, 4, 2])

In [42]:
# Ben missed Monday — represented as 0; Tue=5, Wed=5, Thu=3, Fri=4
ben = np.array([0, 5, 5, 3, 4])

In [43]:
# Carla: Mon=3, Tue=6, Wed=0 (sick), Thu=3, Fri=4
carla = np.array([3, 6, 0, 3, 4])

In [44]:
# Stack all three into a single 2D array: each row = one person, each column = one day
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [45]:
# Total doors knocked per person (sum along axis=1 — across the days)
per_person = np.sum(all_knocks, axis=1)
print(f'Ali knocked on {per_person[0]} doors, Ben on {per_person[1]}, and Carla on {per_person[2]}.')

# Total doors knocked by the whole group
group_total = np.sum(all_knocks)
print(f'The group collectively knocked on {group_total} doors.')

Ali knocked on 21 doors, Ben on 17, and Carla on 16.
The group collectively knocked on 54 doors.


In [46]:
# Daily totals for the group 
daily_totals = np.sum(all_knocks, axis=0)

# Cumulative rolling total of doors knocked day by day
rolling_doors = np.cumsum(daily_totals)

# Every 2 door-knocks = 1 estimated vote, so multiply the rolling total by 0.5
estimated_votes = rolling_doors * 0.5

days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
for day, votes in zip(days, estimated_votes):
    print(f'{day}: estimated cumulative votes turned out = {int(votes)}')

Monday: estimated cumulative votes turned out = 4
Tuesday: estimated cumulative votes turned out = 11
Wednesday: estimated cumulative votes turned out = 17
Thursday: estimated cumulative votes turned out = 22
Friday: estimated cumulative votes turned out = 27
